# Generated by Django 3.2.10 on 2023-01-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nature', models.CharField(max_length=50)),
                ('ability', models.CharField(max_length=50)),
                ('teratype', models.CharField(max_length=50)),
                ('stats', models.TextField()),
                ('skills', models.TextField()),
                ('item', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
